#!/bin/sh
# This script converts Vexcel's *.hdr & *.map files into standard ENVI Files.
#
# Written by Stephen Mather, Nov 2, 2005

FILELIST=`ls *.map | tr '.' ' ' | awk '{ print $1 ; }'`

# For ENVI Files
EXTENSION='.hdr'

echo Creating ENVI Files...
for FILE in $FILELIST
do
#	if [ -f $FILE ]
#	then
		#mv $FILE.hdr $FILE.hdrBAK
		LINES=`grep lines img.0.h | awk '{ print $2 ; }'`
		SAMPLES=`grep pixels img.0.h | awk '{ print $2 ; }'`
		grep min_x $FILE.map | awk '{ print $2 ; }'
		grep max_y $FILE.map | awk '{ print $2 ; }'
		ORIGINALFILE=`grep file img.0.h | awk '{ print $2 ; }'`
		echo	ENVI > img.0$EXTENSION
		echo	'description = { Created from Vexcel *.hdr and *.map files, ' $ORIGINALFILE '}' >> img.0$EXTENSION
		echo	samples = $SAMPLES >> img.0$EXTENSION
		echo	lines = $LINES >> img.0$EXTENSION
		echo	'bands = 1' >> img.0$EXTENSION
		echo	'header offset = 0' >> img.0$EXTENSION
		echo	'file type = ENVI Standard' >> img.0$EXTENSION
		echo	'data type = 2' >> img.0$EXTENSION
		echo	'interleave = bsq' >> img.0$EXTENSION
		echo	'sensor type = RADARSAT' >> img.0$EXTENSION
		echo	'byte order = 1' >> img.0$EXTENSION
#		echo	'map info = { PSG, ' >> $FILE$EXTENSION
		echo img.0$EXTENSION has been created.
#	fi
done


# This script converts Vexcel's *.map files into standard ESRI World Files.
#
# Written by Stephen Mather, Oct 20, 2005

FILELIST=`ls *.map | tr '.' ' ' | awk '{ print $1 ; }'`

	# For ENVI Files
	EXTENSION='.hrw'

#set the pixelsize
	PIXELSIZE=10

echo Creating World Files...
for FILE in $FILELIST
do
#	if [ -f $FILE ]
#	then
		echo	$PIXELSIZE > img.0$EXTENSION
		echo	0 >> img.0$EXTENSION
		echo	0 >> img.0$EXTENSION
		echo	-$PIXELSIZE >> img.0$EXTENSION
		grep min_x $FILE.map | awk '{ print $2 ; }' >> img.0$EXTENSION
		grep max_y $FILE.map | awk '{ print $2 ; }' >> img.0$EXTENSION
		echo img.0$EXTENSION has been created.
#	fi
done
